name: news_app_clean_architecture
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  equatable: ^2.0.5
  floor: any
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.20.5
  get_it: ^7.6.0
  intl: ^0.19.0
  retrofit: ^4.0.1
  sqflite: ^2.3.2

dev_dependencies:
  build_runner: ^2.4.6
  floor_generator: ^1.4.2
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  retrofit_generator: ^8.1.0

flutter:
  uses-material-design: true

  assets:
    - .env

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
